FoodDelivery/Pages/Customer/Cart/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ApplicationCore.Interfaces;
using ApplicationCore.Models;
using FoodDelivery.ViewModels;
using Infrastructure.Utilty;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FoodDelivery.Pages.Customer.Cart
{
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        public IndexModel(IUnitOfWork unitOfWork) => _unitOfWork = unitOfWork;
        public OrderDetailsCartVM OrderDetailsCart { get; set; }

        public void OnGet()
        {
            OrderDetailsCart = new OrderDetailsCartVM()
            {
                OrderHeader = new OrderHeader(),
                ListCart = new List<ShoppingCart>()
            };

            OrderDetailsCart.OrderHeader.OrderTotal = 0;
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                IEnumerable<ShoppingCart> cart = _unitOfWork.ShoppingCart.List(c => c.ApplicationUserId == claim.Value);
                if (cart != null)
                {
                    OrderDetailsCart.ListCart = cart.ToList();
                }

                foreach (var cartList in OrderDetailsCart.ListCart)
                {
                    cartList.MenuItem = _unitOfWork.MenuItem.Get(n => n.Id == cartList.MenuItemId);
                    OrderDetailsCart.OrderHeader.OrderTotal += (cartList.MenuItem.Price * cartList.Count);
                }
            }
        }

        public IActionResult OnPostMinus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.Get(c => c.Id == cartId);
            if (cart.Count == 1)
            {
                _unitOfWork.ShoppingCart.Delete(cart);
            }

            else
            {
                cart.Count -= 1;
                _unitOfWork.ShoppingCart.Update(cart);
            }

            _unitOfWork.Commit();

            var cnt = _unitOfWork.ShoppingCart.List(u => u.ApplicationUserId == cart.ApplicationUserId).Count();
            HttpContext.Session.SetInt32(SD.ShoppingCart, cnt);
            return RedirectToPage("/Customer/Cart/Index");
        }

        public IActionResult OnPostPlus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.Get(c => c.Id == cartId);
            cart.Count += 1;
            _unitOfWork.ShoppingCart.Update(cart);

            _unitOfWork.Commit();

            return RedirectToPage("/Customer/Cart/Index");
        }

        public IActionResult OnPostRemove(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.Get(c => c.Id == cartId);
            _unitOfWork.ShoppingCart.Delete(cart);
            _unitOfWork.Commit();

            var cnt = _unitOfWork.ShoppingCart.List(u => u.ApplicationUserId == cart.ApplicationUserId).Count();
            HttpContext.Session.SetInt32(SD.ShoppingCart, cnt);
            return RedirectToPage("/Customer/Cart/Index");
        }
    }
}

FoodDelivery/Pages/Customer/Cart/OrderConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FoodDelivery.Pages.Customer.Cart
{
	public class OrderConfirmationModel : PageModel
    {
        [BindProperty]
        public int OrderId { get; set; }

        public void OnGet(int id)
        {
            OrderId = id;
        }
    }
}

FoodDelivery/Pages/Customer/Cart/Summary.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ApplicationCore.Interfaces;
using ApplicationCore.Models;
using FoodDelivery.ViewModels;
using Infrastructure.Utilty;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripe;

namespace FoodDelivery.Pages.Customer.Cart
{
	public class SummaryModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        public SummaryModel(IUnitOfWork unitOfWork) => _unitOfWork = unitOfWork;
        private int i = 1;

        [BindProperty]
        public OrderDetailsCartVM OrderDetailsCart { get; set; }

        public void OnGet()
        {
            OrderDetailsCart = new OrderDetailsCartVM()
            {
                OrderHeader = new OrderHeader(),
                ListCart = new List<ShoppingCart>()
            };
            OrderDetailsCart.OrderHeader.OrderTotal = 0;
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if(claim != null)
            {
                IEnumerable<ShoppingCart> cart = _unitOfWork.ShoppingCart.List(c => c.ApplicationUserId == claim.Value);
                if(cart != null)
                {
                    OrderDetailsCart.ListCart = cart.ToList();
                }
                foreach(var cartList in OrderDetailsCart.ListCart)
                {
                    cartList.MenuItem = _unitOfWork.MenuItem.Get(n => n.Id == cartList.MenuItemId);
                    OrderDetailsCart.OrderHeader.OrderTotal += (cartList.MenuItem.Price * cartList.Count);
                }
                OrderDetailsCart.OrderHeader.OrderTotal += OrderDetailsCart.OrderHeader.OrderTotal * SD.SalesTaxPercent;
                ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(c => c.Id == claim.Value);
                OrderDetailsCart.OrderHeader.DeliveryName = applicationUser.FullName;
                OrderDetailsCart.OrderHeader.PhoneNumber = applicationUser.PhoneNumber;
                OrderDetailsCart.OrderHeader.DeliveryTime = DateTime.Now;
                OrderDetailsCart.OrderHeader.DeliveryDate = DateTime.Now;
                OrderDetailsCart.OrderHeader.TransactionsId = i.ToString();
                i++;
            }
        }

        public IActionResult OnPost(string stripeToken)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            OrderDetailsCart.ListCart = _unitOfWork.ShoppingCart.List(c => c.ApplicationUserId == claim.Value).ToList();
            OrderDetailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            OrderDetailsCart.OrderHeader.OrderDate = DateTime.Now;
            OrderDetailsCart.OrderHeader.UserId = claim.Value;
            OrderDetailsCart.OrderHeader.Status = SD.StatusSubmitted;
            OrderDetailsCart.OrderHeader.DeliveryTime = Convert.ToDateTime(OrderDetailsCart.OrderHeader.DeliveryDate.ToShortDateString() + " " + OrderDetailsCart.OrderHeader.DeliveryTime.ToShortTimeString());
            OrderDetailsCart.OrderHeader.TransactionsId = i.ToString();
            i++;
            List<OrderDetails> orderDetailsList = new List<OrderDetails>();
            _unitOfWork.OrderHeader.Add(OrderDetailsCart.OrderHeader);
            _unitOfWork.Commit();

            foreach(var item in OrderDetailsCart.ListCart)
            {
                item.MenuItem = _unitOfWork.MenuItem.Get(m => m.Id == item.MenuItemId);
                OrderDetails orderDetails = new OrderDetails
                {
                    MenuItemId = item.MenuItemId,
                    OrderId = OrderDetailsCart.OrderHeader.Id,
                    Name = item.MenuItem.Name,
                    Price = item.MenuItem.Price,
                    Count = item.Count
                };

                OrderDetailsCart.OrderHeader.OrderTotal += (orderDetails.Count * orderDetails.Price) * (1 + SD.SalesTaxPercent);
                _unitOfWork.OrderDetails.Add(orderDetails);
            }

            OrderDetailsCart.OrderHeader.OrderTotal = Convert.ToDouble(String.Format("{0:.##}", OrderDetailsCart.OrderHeader.OrderTotal));

            HttpContext.Session.SetInt32(SD.ShoppingCart, 0);
            _unitOfWork.Commit();

            //calling stripe pop up api through JS

            if(stripeToken != null)
            {
                var options = new ChargeCreateOptions
                {
                    Amount = Convert.ToInt32(OrderDetailsCart.OrderHeader.OrderTotal * 100), //requires in cents
                    Currency = "usd",
                    Description = "Order Id: " + OrderDetailsCart.OrderHeader.Id,
                    Source = stripeToken
                };

                var service = new ChargeService();
                Charge charge = service.Create(options);
                OrderDetailsCart.OrderHeader.TransactionsId = charge.Id;

                if(charge.Status.ToLower() == "succeeded")
                {
                    OrderDetailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusApproved;
                }
                else
                {
                    OrderDetailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusRejected;
                }
            }
            _unitOfWork.Commit();
            return RedirectToPage("/Customer/Cart/Orderconfirmation", new { id = OrderDetailsCart.OrderHeader.Id });
        }
    }
}

FoodDelivery/Pages/Customer/Home/Details.cshtml.cs
using ApplicationCore.Interfaces;
using ApplicationCore.Models;
using Infrastructure.Utilty;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace FoodDelivery.Pages.Customer.Home
{
    public class DetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        public DetailsModel(IUnitOfWork unitOfWork) => _unitOfWork = unitOfWork;
        [BindProperty]
        public ShoppingCart ShoppingCartObj { get; set; }
        public async Task OnGet(int id)
        {
            ShoppingCartObj = new ShoppingCart()
            {
                MenuItem = await _unitOfWork.MenuItem.GetAsync(m => m.Id == id, false, "Category,FoodType")
            };

            ShoppingCartObj.MenuItemId = id;


        }

        public IActionResult OnPost()
        {
            //if(ShoppingCartObj.ApplicationUserId == null)
            //{
            //    return Redirect("~/Identity/Account/Login");
            //}

            //get the applicationuserid from AspNetUsers table
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ShoppingCartObj.ApplicationUserId = claim.Value;

            //if there's already a cart for this user, retrieve it
            ShoppingCart cartFromDb = _unitOfWork.
                ShoppingCart.Get(c => c.ApplicationUserId == ShoppingCartObj.ApplicationUserId
                && c.MenuItemId == ShoppingCartObj.MenuItemId);

            if (cartFromDb == null)
            {
                _unitOfWork.ShoppingCart.Add(ShoppingCartObj);
            }
            else
            {
                cartFromDb.Count += ShoppingCartObj.Count;
                _unitOfWork.ShoppingCart.Update(cartFromDb);
            }
            _unitOfWork.Commit();

            //this is for our Icon on the shared layout menu (3)
            var count = _unitOfWork.ShoppingCart.List(c => c.ApplicationUserId == ShoppingCartObj.ApplicationUserId).Count();
            HttpContext.Session.SetInt32(SD.ShoppingCart, count);
            return RedirectToPage("./Index");


        }

    }
}

FoodDelivery/Pages/Customer/Home/Index.cshtml.cs
using ApplicationCore.Interfaces;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FoodDelivery.Pages.Customer.Home
{
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitofWork;
        public IndexModel(IUnitOfWork unitofWork) => _unitofWork = unitofWork;

        public IEnumerable<MenuItem> MenuItemList { get; set; }
        public IEnumerable<Category> CategoryList { get; set; }

        public void OnGet()
        {
            MenuItemList = _unitofWork.MenuItem.List(null, null, "Category,FoodType");
            CategoryList = _unitofWork.Category.List(null, q => q.DisplayOrder, null);
        }
    }
}

FoodDelivery/Pages/Customer/Cart/Index.cshtml
@page
@model FoodDelivery.Pages.Customer.Cart.IndexModel
@{
    ViewData["Title"] = "Index";
}

<form method="post">

    <br />

    @if (Model.OrderDetailsCart.ListCart.Count != 0)
    {

        <input asp-for="@Model.OrderDetailsCart.ListCart[0].ApplicationUserId" hidden />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Shopping Cart
                        </div>
                        <div class="col-6 text-end">
                            <a asp-page="../Home/Index" class="btn btn-outline-info btn-sm">Continue Shopping</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @foreach (var item in Model.OrderDetailsCart.ListCart)
                        {
                            <div class="row">
                                <div class="d-none d-lg-block col-lg-2 text-center py-2">
                                    <img src="@item.MenuItem.Image" class="rounded" width="120" height="80" />
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-left">
                                    <h4><strong>@item.MenuItem.Name</strong></h4>
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                    <div class="col-4 text-md-right" style="padding-top:5px;">
                                        <h6><strong>$@item.MenuItem.Price.ToString("0.00") <span class="text-muted">x</span> @item.Count </strong></h6>
                                    </div>
                                    <div class="col-6 col-sm-4 col-lg-6">
                                        <div class="float-right mx-1">
                                            <button type="submit" class="btn btn-primary" asp-page-handler="plus" asp-route-cartId="@item.Id">
                                                <i class="fas fa-plus"></i>
                                            </button>
                                        </div>
                                        <div class="float-right mx-1">
                                            <button type="submit" class="btn btn-danger" asp-page-handler="minus" asp-route-cartId="@item.Id">
                                                <i class="fas fa-minus"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="col-2 col-sm-4 col-lg-2 text-right">
                                        <button type="submit" class="btn btn-outline-danger" asp-page-handler="remove" asp-route-cartId="@item.Id">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <hr />
                        }
                        <div class="row">
                            <div class="col-12 col-md-5">

                            </div>
                            <div class="col-12 col-md-6 offset-md-1 col-lg-4 offset-lg-3 pr-4">
                                <ul class="list-group">
                                    <li class="list-group-item d-flex justify-content-between bg-light">
                                        <span class="text-info"> SubTotal (USD)</span>
                                        <strong class="text-info">$ <span id="txtOrderTotal">@Model.OrderDetailsCart.OrderHeader.OrderTotal.ToString("0.00")</span></strong>
                                    </li>
                                </ul>
                            </div>
                        </div>


                    </div>
                    <div class="card-footer">
                        <div class="col-12 col-lg-4 offset-lg-8 col-md-6 offset-md-6">
                            <a asp-page="Summary" class="btn btn-success form-control">Summary</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div>
            Please add items to shopping cart.
        </div>
    }
</form>

FoodDelivery/Pages/Customer/Cart/OrderConfirmation.cshtml
@page
@model FoodDelivery.Pages.Customer.Cart.OrderConfirmationModel
@{ ViewData["Title"] = "OrderConfirmation";}

<div class="container row">
    <div class="col-12 text-center">
        <h1 class="text-primary text-center">Order Placed Successfully!</h1>
        Your Order Number is : @Model.OrderId <br /><br />
        <img src="~/images/logo.gif" style="width:100%" />
    </div>
    <div class="col-12 text-center" style="color:maroon">
        <br />
        Your order has been placed successfully! <br />
        Our friendly driver will arrive on time with your hot delicious food!
    </div>
</div>

FoodDelivery/Pages/Customer/Cart/Summary.cshtml
@page
@model FoodDelivery.Pages.Customer.Cart.SummaryModel
@using Infrastructure.Services
@using Infrastructure.Utilty
@using Microsoft.Extensions.Options
@inject IOptions<Infrastructure.Services.StripeSettings> Stripe

@{ ViewData["Title"] = "Summary"; }

<form method="post">
    <br />

    @if (Model.OrderDetailsCart.ListCart.Count > 0)
    {
        <input asp-for="@Model.OrderDetailsCart.ListCart[0].ApplicationUserId" hidden />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Order Summary
                        </div>
                        <div class="col-6 text-end">
                            <a asp-page="Index" class="btn btn-outline-info btn-sm">Back to Cart</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="container rounded p-2">
                            <div class="row">
                                <div class="col-12 col-lg-6 pb-4">
                                    <div class="row">
                                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                                            <span class="text-info">Delivery Details:</span>
                                        </h4>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Name</label>
                                        </div>
                                        <div class="col-9">
                                            <input id="txtName" asp-for="@Model.OrderDetailsCart.OrderHeader.DeliveryName" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Phone Number</label>
                                        </div>
                                        <div class="col-9">
                                            <input id="txtPhone" asp-for="@Model.OrderDetailsCart.OrderHeader.PhoneNumber" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Delivery Date</label>
                                        </div>
                                        <div class="col-9">
                                            <input id="datepicker" value="" asp-for="@Model.OrderDetailsCart.OrderHeader.DeliveryDate" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Delivery Time</label>
                                        </div>
                                        <div class="col-9">
                                            <input id="timepicker" value="" asp-for="@Model.OrderDetailsCart.OrderHeader.DeliveryTime" type="text" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row my-1">
                                        <div class="col-3">
                                            <label>Additional Instructions: </label>
                                        </div>
                                        <div class="col-9">
                                            <textarea asp-for="@Model.OrderDetailsCart.OrderHeader.Comments" style="height:100px;" class="form-control"></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-12 col-lg-5 offset-lg-1">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info">Order Summary:</span>
                                    </h4>
                                    <ul class="list-group mb-3">
                                        @{ var total = 0.0;}
                                        @foreach (var details in Model.OrderDetailsCart.ListCart)
                                        {
                                            <li class="list-group-item d-flex justify-content-between">
                                                <div>
                                                    <h6 class="my-0">@details.MenuItem.Name</h6>
                                                    <small class="text-muted">Quantity: @details.Count</small>
                                                </div>
                                                <span class="text-muted">$@((details.MenuItem.Price * details.Count).ToString("0.00"))</span>
                                                @{ total += (details.MenuItem.Price * details.Count);}
                                            </li>
}
                                        <li class="list-group-item d-flex justify-content-between bg-light">
                                            <small class="text-info">Sales Tax (@SD.SalesTaxRate%)</small>
                                            @{ var salesTax = Math.Round((total * SD.SalesTaxPercent), 2);}
                                            <strong class="text-info">$@salesTax.ToString("0.00")</strong>
                                        </li>
                                        <li class="list-group-item d-flex justify-content-between bg-light">
                                            <small class="text-info">Total (USD)</small>
                                            @{ total += salesTax;}
                                            <strong class="text-info">$@total.ToString("0.00")</strong>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-12 col-md-4 offset-md-8">
                                @{ var OrderTotalForStripe = Math.Round((Model.OrderDetailsCart.OrderHeader.OrderTotal * 100), 0); }
                                <script src="https://checkout.stripe.com/checkout.js"
                                        class="stripe-button"
                                        data-key="pk_test_51KWZeVH3hlqhRjKxb0KeSq2jIoEZA535afkyzYJ4VldksbspBygF54zgYHz1anXfFJ6MhZxAZvTim6LL57WpytDg00WxVkmtKJ"
                                        data-amount="@OrderTotalForStripe"
                                        data-name="4790 Food Delivery Demo"
                                        data-label="Place Order"
                                        data-description="Good Food, Delivered Fast."
                                        data-locale="auto"
                                        data-allow-remember-me="false"
                                        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"></script>

                                <script>document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';</script>
                                <button type="submit" id="btnPlaceOrder" onclick="return validateInput()" value="Place Order" class="btn btn-success form-control">Place Order</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>}
</form>

@section Scripts{
    <script>$(function () {
                $("#datepicker").datepicker({ minDate: 1, maxDate: "+1W" });
                $("#timepicker").timepicker({ 'minTime': '11:00 AM', 'maxTime': '9:00 PM', step: '30' });
            });


            function validateInput() {
                var time = document.getElementById("timepicker").value;
                var dt = document.getElementById("datepicker").value;
                var name = document.getElementById("txtName").value;
                var phone = document.getElementById("txtPhone").value;

                if (dt.toString() == '') {
                    swal("Error", "Please select Delivery Date", "error");
                    return false;
                }
                if (time.toString() == '') {
                    swal("Error", "Please select Delivery Time", "error");
                    return false;
                }
                if (name.toString() == '') {
                    swal("Error", "Please enter a Name", "error");
                    return false;
                }
                if (phone.toString() == '') {
                    swal("Error", "Please enter Phone Number", "error");
                    return false;
                }
                return true;
            }</script>
}